# Forge/Gradle settings
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft/Forge versions
minecraft_version=1.20.1
forge_version=47.3.5
mappings_channel=official
mappings_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
loader_version_range=[47,)

# Mod metadata
mod_id=yigd
archives_base_name=youre-in-grave-danger-forge
mod_name=You're in Grave Danger
mod_license=MIT
mod_version=2.0.21
mod_group_id=com.b1n_ry.yigd
mod_authors=b1n_ry
mod_description=Adds graves and some other stuff to the game

# Dependency versions
config_version=11.1.118
curios_version=5.9.1+1.20.1
accessories_version=1.0.0-beta.47+1.20.1-mojmap
travelers_backpack_version=9nwiWyA3
cosmetic_armor_version=237307:5610814
