org.gradle.jvmargs=-Xmx1G -XX:ActiveProcessorCount=2
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.caching=true
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.1.3)
neo_version=26.1.2.114
neo_version_range=[26.1.2.114,26.1.3)
loader_version_range=[4,)
mod_id=yigd
mod_name=You're in Grave Danger
mod_license=MIT
mod_version=2.0.22
mod_group_id=com.b1n_ry.yigd
mod_authors=b1n_ry, nullifyac
mod_description=Graves preserve your inventory and experience when you die, with persistent recovery records.
config_version=26.1.154
curios_version=15.0.0+26.1.2
